# Generated by Django 4.2.6 on 2023-10-25 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tech', '0002_blogpost_categories_blogpost_image_blogpost_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='tags',
        ),
    ]
