version: '3.8'

services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: localhost:5000/bloggersunity-web:latest
    command: ./docker/entrypoint.sh
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    volumes:
      - ..:/app
    ports:
      - "8000:8000"
