version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: ./entrypoint.sh
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
    ports:
      - "8000:8000"