services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: localhost:5000/bloggersunity-web:latest
    command: ./docker/entrypoint.sh
    volumes:
      - ..:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:latest
    env_file:
      - ../.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
