apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bloggersunity-application
  namespace: argocd
spec:
  project: default
  source: 
    repoURL: https://github.com/praks7v/BloggersUnity.git
    targetRevision: HEAD
    path: argocd/dev
  destination: 
    server: https://kubernetes.default.svc
    namespace: bloggersunity
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
  
